# Vantagens de Usar um Makefile
# Automatização: Automatiza tarefas repetitivas, tornando o desenvolvimento mais eficiente.
# Consistência: Garante que todos os membros da equipe utilizem os mesmos comandos e configurações.
# Simplicidade: Simplifica comandos longos e complexos em comandos curtos e fáceis de lembrar.
# # Flexibilidade: Pode ser usado para definir uma ampla variedade de tarefas, desde a compilação até o deployment.

# Estrutura de um Makefile
# Um Makefile é composto por uma série de regras. Cada regra possui um alvo (target), uma ou mais dependências (prerequisites) e uma série de comandos que são executados para construir o alvo. A sintaxe básica é:

# makefile
# target: prerequisites
#     command

run:
	@uvicorn main:app --reload